server:
  port: 3001
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signer-key: ${JWT_SECRET}
  valid-duration:
  refreshable-duration:
app:
  cors:
    origin: ${CORS_ORIGIN}

sepay:
  merchant-id: ${SEPAY_MERCHANT_ID}
  secret-key: ${SEPAY_SECRET_KEY}
  env: